export const districts = [
  "Dhaka",
  "Chittagong",
  "Rajshahi",
  "Khulna",
  "Barisal",
  "Sylhet",
  "Rangpur",
  "Mymensingh",
  "Comilla",
  "Feni",
  "Brahmanbaria",
  "Rangamati",
  "Noakhali",
  "Chandpur",
  "Lakshmipur",
  "Cox's Bazar",
  "Bandarban",
  "Khagrachhari",
  "Bogura",
  "Joypurhat",
  "Naogaon",
  "Natore",
  "Nawabganj",
  "Pabna",
  "Rajshahi",
  "Sirajganj",
  "Dinajpur",
  "Gaibandha",
  "Kurigram",
  "Lalmonirhat",
  "Nilphamari",
  "Panchagarh",
  "Rangpur",
  "Thakurgaon",
]

export const upazilas = {
  Dhaka: ["Dhanmondi", "Gulshan", "Banani", "Uttara", "Mirpur", "Mohammadpur", "Old Dhaka", "Wari"],
  Chittagong: ["Agrabad", "Nasirabad", "Halishahar", "Panchlaish", "Khulshi", "Bayazid", "Chandgaon"],
  Rajshahi: ["Boalia", "Motihar", "Rajpara", "Shah Makhdum", "Chandrima"],
  Khulna: ["Khalishpur", "Sonadanga", "Boyra", "Khan Jahan Ali", "Daulatpur"],
  Barisal: ["Sadar", "Babuganj", "Bakerganj", "Banaripara", "Gaurnadi"],
  Sylhet: ["Sadar", "Beanibazar", "Bishwanath", "Companiganj", "Fenchuganj"],
  Rangpur: ["Sadar", "Badarganj", "Gangachara", "Kaunia", "Mithapukur"],
  Mymensingh: ["Sadar", "Bhaluka", "Dhobaura", "Fulbaria", "Gaffargaon"],
}
