// Bangladesh Geocode Data - Complete Districts and Upazilas
// Source: https://github.com/nuhil/bangladesh-geocode

export const districts = [
  // Barisal Division
  "Barguna",
  "Barisal",
  "Bhola",
  "Jhalokati",
  "Patuakhali",
  "Pirojpur",

  // Chittagong Division
  "Bandarban",
  "Brahmanbaria",
  "Chandpur",
  "Chittagong",
  "Comilla",
  "Cox's Bazar",
  "Feni",
  "Khagrachhari",
  "Lakshmipur",
  "Noakhali",
  "Rangamati",

  // Dhaka Division
  "Dhaka",
  "Faridpur",
  "Gazipur",
  "Gopalganj",
  "Kishoreganj",
  "Madaripur",
  "Manikganj",
  "Munshiganj",
  "Narayanganj",
  "Narsingdi",
  "Rajbari",
  "Shariatpur",
  "Tangail",

  // Khulna Division
  "Bagerhat",
  "Chuadanga",
  "Jessore",
  "Jhenaidah",
  "Khulna",
  "Kushtia",
  "Magura",
  "Meherpur",
  "Narail",
  "Satkhira",

  // Mymensingh Division
  "Jamalpur",
  "Mymensingh",
  "Netrakona",
  "Sherpur",

  // Rajshahi Division
  "Bogra",
  "Chapainawabganj",
  "Joypurhat",
  "Naogaon",
  "Natore",
  "Pabna",
  "Rajshahi",
  "Sirajganj",

  // Rangpur Division
  "Dinajpur",
  "Gaibandha",
  "Kurigram",
  "Lalmonirhat",
  "Nilphamari",
  "Panchagarh",
  "Rangpur",
  "Thakurgaon",

  // Sylhet Division
  "Habiganj",
  "Moulvibazar",
  "Sunamganj",
  "Sylhet",
]

export const upazilas = {
  // Barisal Division
  Barguna: ["Amtali", "Bamna", "Barguna Sadar", "Betagi", "Patharghata", "Taltali"],
  Barisal: [
    "Agailjhara",
    "Babuganj",
    "Bakerganj",
    "Banaripara",
    "Barisal Sadar",
    "Gaurnadi",
    "Hizla",
    "Mehendiganj",
    "Muladi",
    "Wazirpur",
  ],
  Bhola: ["Bhola Sadar", "Burhanuddin", "Char Fasson", "Daulatkhan", "Lalmohan", "Manpura", "Tazumuddin"],
  Jhalokati: ["Jhalokati Sadar", "Kathalia", "Nalchity", "Rajapur"],
  Patuakhali: ["Bauphal", "Dashmina", "Dumki", "Galachipa", "Kalapara", "Mirzaganj", "Patuakhali Sadar", "Rangabali"],
  Pirojpur: ["Bhandaria", "Kawkhali", "Mathbaria", "Nazirpur", "Nesarabad", "Pirojpur Sadar", "Zianagar"],

  // Chittagong Division
  Bandarban: ["Ali Kadam", "Bandarban Sadar", "Lama", "Naikhongchhari", "Rowangchhari", "Ruma", "Thanchi"],
  Brahmanbaria: [
    "Akhaura",
    "Bancharampur",
    "Brahmanbaria Sadar",
    "Kasba",
    "Nabinagar",
    "Nasirnagar",
    "Sarail",
    "Ashuganj",
    "Bijoynagar",
  ],
  Chandpur: [
    "Chandpur Sadar",
    "Faridganj",
    "Haimchar",
    "Haziganj",
    "Kachua",
    "Matlab Dakshin",
    "Matlab Uttar",
    "Shahrasti",
  ],
  Chittagong: [
    "Anwara",
    "Banshkhali",
    "Boalkhali",
    "Chandanaish",
    "Chittagong Sadar",
    "Fatikchhari",
    "Hathazari",
    "Lohagara",
    "Mirsharai",
    "Patiya",
    "Rangunia",
    "Raozan",
    "Sandwip",
    "Satkania",
    "Sitakunda",
  ],
  Comilla: [
    "Barura",
    "Brahmanpara",
    "Burichang",
    "Chandina",
    "Chauddagram",
    "Daudkandi",
    "Debidwar",
    "Homna",
    "Laksam",
    "Muradnagar",
    "Nangalkot",
    "Comilla Sadar",
    "Meghna",
    "Monohargonj",
    "Sadarsouth",
    "Titas",
    "Comilla Sadar Dakshin",
  ],
  "Cox's Bazar": ["Chakaria", "Cox's Bazar Sadar", "Kutubdia", "Maheshkhali", "Ramu", "Teknaf", "Ukhia", "Pekua"],
  Feni: ["Chhagalnaiya", "Daganbhuiyan", "Feni Sadar", "Fulgazi", "Parshuram", "Sonagazi"],
  Khagrachhari: [
    "Dighinala",
    "Khagrachhari Sadar",
    "Lakshmichhari",
    "Mahalchhari",
    "Manikchhari",
    "Matiranga",
    "Panchhari",
    "Ramgarh",
  ],
  Lakshmipur: ["Lakshmipur Sadar", "Raipur", "Ramganj", "Ramgati", "Kamalnagar"],
  Noakhali: [
    "Begumganj",
    "Noakhali Sadar",
    "Chatkhil",
    "Companiganj",
    "Hatiya",
    "Senbagh",
    "Sonaimuri",
    "Subarnachar",
    "Kabirhat",
  ],
  Rangamati: [
    "Bagaichhari",
    "Barkal",
    "Kawkhali",
    "Belaichhari",
    "Kaptai",
    "Juraichhari",
    "Langadu",
    "Naniyachar",
    "Rajasthali",
    "Rangamati Sadar",
  ],

  // Dhaka Division
  Dhaka: ["Dhamrai", "Dohar", "Keraniganj", "Nawabganj", "Savar"],
  Faridpur: [
    "Alfadanga",
    "Bhanga",
    "Boalmari",
    "Charbhadrasan",
    "Faridpur Sadar",
    "Madhukhali",
    "Nagarkanda",
    "Sadarpur",
    "Saltha",
  ],
  Gazipur: ["Gazipur Sadar", "Kaliakair", "Kaliganj", "Kapasia", "Sreepur"],
  Gopalganj: ["Gopalganj Sadar", "Kashiani", "Kotalipara", "Muksudpur", "Tungipara"],
  Kishoreganj: [
    "Austagram",
    "Bajitpur",
    "Bhairab",
    "Hossainpur",
    "Itna",
    "Karimganj",
    "Katiadi",
    "Kishoreganj Sadar",
    "Kuliarchar",
    "Mithamain",
    "Nikli",
    "Pakundia",
    "Tarail",
  ],
  Madaripur: ["Kalkini", "Madaripur Sadar", "Rajoir", "Shibchar"],
  Manikganj: ["Daulatpur", "Ghior", "Harirampur", "Manikgonj Sadar", "Saturia", "Shivalaya", "Singair"],
  Munshiganj: ["Gazaria", "Lohajang", "Munshiganj Sadar", "Serajdikhan", "Sreenagar", "Tongibari"],
  Narayanganj: ["Araihazar", "Bandar", "Narayanganj Sadar", "Rupganj", "Sonargaon"],
  Narsingdi: ["Belabo", "Monohardi", "Narsingdi Sadar", "Palash", "Raipura", "Shibpur"],
  Rajbari: ["Baliakandi", "Goalandaghat", "Pangsha", "Rajbari Sadar", "Kalukhali"],
  Shariatpur: ["Bhedarganj", "Damudya", "Gosairhat", "Naria", "Shariatpur Sadar", "Zajira"],
  Tangail: [
    "Basail",
    "Bhuapur",
    "Delduar",
    "Ghatail",
    "Gopalpur",
    "Kalihati",
    "Madhupur",
    "Mirzapur",
    "Nagarpur",
    "Sakhipur",
    "Tangail Sadar",
    "Dhanbari",
  ],

  // Khulna Division
  Bagerhat: [
    "Bagerhat Sadar",
    "Chitalmari",
    "Fakirhat",
    "Kachua",
    "Mollahat",
    "Mongla",
    "Morrelganj",
    "Rampal",
    "Sarankhola",
  ],
  Chuadanga: ["Alamdanga", "Chuadanga Sadar", "Damurhuda", "Jibannagar"],
  Jessore: [
    "Abhaynagar",
    "Bagherpara",
    "Chaugachha",
    "Jhikargacha",
    "Keshabpur",
    "Jessore Sadar",
    "Manirampur",
    "Sharsha",
  ],
  Jhenaidah: ["Harinakunda", "Jhenaidah Sadar", "Kaliganj", "Kotchandpur", "Maheshpur", "Shailkupa"],
  Khulna: ["Batiaghata", "Dacope", "Dumuria", "Dighalia", "Koyra", "Paikgachha", "Phultala", "Rupsa", "Terokhada"],
  Kushtia: ["Bheramara", "Daulatpur", "Khoksa", "Kumarkhali", "Kushtia Sadar", "Mirpur"],
  Magura: ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"],
  Meherpur: ["Gangni", "Meherpur Sadar", "Mujibnagar"],
  Narail: ["Kalia", "Lohagara", "Narail Sadar"],
  Satkhira: ["Assasuni", "Debhata", "Kalaroa", "Kaliganj", "Satkhira Sadar", "Shyamnagar", "Tala"],

  // Mymensingh Division
  Jamalpur: ["Baksiganj", "Dewanganj", "Islampur", "Jamalpur Sadar", "Madarganj", "Melandaha", "Sarishabari"],
  Mymensingh: [
    "Bhaluka",
    "Dhobaura",
    "Fulbaria",
    "Gaffargaon",
    "Gouripur",
    "Haluaghat",
    "Ishwarganj",
    "Mymensingh Sadar",
    "Muktagachha",
    "Nandail",
    "Phulpur",
    "Trishal",
  ],
  Netrakona: [
    "Atpara",
    "Barhatta",
    "Durgapur",
    "Khaliajuri",
    "Kalmakanda",
    "Kendua",
    "Madan",
    "Mohanganj",
    "Netrakona Sadar",
    "Purbadhala",
  ],
  Sherpur: ["Jhenaigati", "Nakla", "Nalitabari", "Sherpur Sadar", "Sreebardi"],

  // Rajshahi Division
  Bogra: [
    "Adamdighi",
    "Bogra Sadar",
    "Dhunat",
    "Dhupchanchia",
    "Gabtali",
    "Kahaloo",
    "Nandigram",
    "Sariakandi",
    "Shajahanpur",
    "Sherpur",
    "Shibganj",
    "Sonatola",
  ],
  Chapainawabganj: ["Bholahat", "Gomastapur", "Nachole", "Chapainawabganj Sadar", "Shibganj"],
  Joypurhat: ["Akkelpur", "Joypurhat Sadar", "Kalai", "Khetlal", "Panchbibi"],
  Naogaon: [
    "Atrai",
    "Badalgachhi",
    "Manda",
    "Dhamoirhat",
    "Mohadevpur",
    "Naogaon Sadar",
    "Niamatpur",
    "Patnitala",
    "Porsha",
    "Raninagar",
    "Sapahar",
  ],
  Natore: ["Bagatipara", "Baraigram", "Gurudaspur", "Lalpur", "Natore Sadar", "Singra"],
  Pabna: ["Atgharia", "Bera", "Bhangura", "Chatmohar", "Faridpur", "Ishwardi", "Pabna Sadar", "Santhia", "Sujanagar"],
  Rajshahi: ["Bagha", "Bagmara", "Charghat", "Durgapur", "Godagari", "Mohanpur", "Paba", "Puthia", "Tanore"],
  Sirajganj: [
    "Belkuchi",
    "Chauhali",
    "Kamarkhanda",
    "Kazipur",
    "Raiganj",
    "Shahjadpur",
    "Sirajganj Sadar",
    "Tarash",
    "Ullahpara",
  ],

  // Rangpur Division
  Dinajpur: [
    "Birampur",
    "Birganj",
    "Biral",
    "Bochaganj",
    "Chirirbandar",
    "Phulbari",
    "Ghoraghat",
    "Hakimpur",
    "Kaharole",
    "Khansama",
    "Dinajpur Sadar",
    "Nawabganj",
    "Parbatipur",
  ],
  Gaibandha: ["Fulchhari", "Gaibandha Sadar", "Gobindaganj", "Palashbari", "Sadullapur", "Sughatta", "Sundarganj"],
  Kurigram: [
    "Bhurungamari",
    "Char Rajibpur",
    "Chilmari",
    "Kurigram Sadar",
    "Nageshwari",
    "Phulbari",
    "Rajarhat",
    "Raomari",
    "Ulipur",
  ],
  Lalmonirhat: ["Aditmari", "Hatibandha", "Kaliganj", "Lalmonirhat Sadar", "Patgram"],
  Nilphamari: ["Dimla", "Domar", "Jaldhaka", "Kishoreganj", "Nilphamari Sadar", "Saidpur"],
  Panchagarh: ["Atwari", "Boda", "Debiganj", "Panchagarh Sadar", "Tetulia"],
  Rangpur: ["Badarganj", "Gangachara", "Kaunia", "Rangpur Sadar", "Mithapukur", "Pirgachha", "Pirganj", "Taraganj"],
  Thakurgaon: ["Baliadangi", "Haripur", "Pirganj", "Ranisankail", "Thakurgaon Sadar"],

  // Sylhet Division
  Habiganj: [
    "Ajmiriganj",
    "Bahubal",
    "Baniyachong",
    "Chunarughat",
    "Habiganj Sadar",
    "Lakhai",
    "Madhabpur",
    "Nabiganj",
  ],
  Moulvibazar: ["Barlekha", "Juri", "Kamalganj", "Kulaura", "Moulvibazar Sadar", "Rajnagar", "Sreemangal"],
  Sunamganj: [
    "Bishwamvarpur",
    "Chhatak",
    "Derai",
    "Dharamapasha",
    "Dowarabazar",
    "Jagannathpur",
    "Jamalganj",
    "Sulla",
    "Sunamganj Sadar",
    "Tahirpur",
    "South Sunamganj",
  ],
  Sylhet: [
    "Balaganj",
    "Beanibazar",
    "Bishwanath",
    "Companigonj",
    "Dakshin Surma",
    "Fenchuganj",
    "Golapganj",
    "Gowainghat",
    "Jaintiapur",
    "Kanaighat",
    "Osmani Nagar",
    "Sylhet Sadar",
    "Zakiganj",
  ],
}

// Helper function to get all districts sorted alphabetically
export const getAllDistricts = () => {
  return districts.sort()
}

// Helper function to get upazilas for a specific district
export const getUpazilasForDistrict = (district) => {
  return upazilas[district] || []
}

// Helper function to get division for a district
export const getDivisionForDistrict = (district) => {
  const divisionMap = {
    // Barisal Division
    Barguna: "Barisal",
    Barisal: "Barisal",
    Bhola: "Barisal",
    Jhalokati: "Barisal",
    Patuakhali: "Barisal",
    Pirojpur: "Barisal",

    // Chittagong Division
    Bandarban: "Chittagong",
    Brahmanbaria: "Chittagong",
    Chandpur: "Chittagong",
    Chittagong: "Chittagong",
    Comilla: "Chittagong",
    "Cox's Bazar": "Chittagong",
    Feni: "Chittagong",
    Khagrachhari: "Chittagong",
    Lakshmipur: "Chittagong",
    Noakhali: "Chittagong",
    Rangamati: "Chittagong",

    // Dhaka Division
    Dhaka: "Dhaka",
    Faridpur: "Dhaka",
    Gazipur: "Dhaka",
    Gopalganj: "Dhaka",
    Kishoreganj: "Dhaka",
    Madaripur: "Dhaka",
    Manikganj: "Dhaka",
    Munshiganj: "Dhaka",
    Narayanganj: "Dhaka",
    Narsingdi: "Dhaka",
    Rajbari: "Dhaka",
    Shariatpur: "Dhaka",
    Tangail: "Dhaka",

    // Khulna Division
    Bagerhat: "Khulna",
    Chuadanga: "Khulna",
    Jessore: "Khulna",
    Jhenaidah: "Khulna",
    Khulna: "Khulna",
    Kushtia: "Khulna",
    Magura: "Khulna",
    Meherpur: "Khulna",
    Narail: "Khulna",
    Satkhira: "Khulna",

    // Mymensingh Division
    Jamalpur: "Mymensingh",
    Mymensingh: "Mymensingh",
    Netrakona: "Mymensingh",
    Sherpur: "Mymensingh",

    // Rajshahi Division
    Bogra: "Rajshahi",
    Chapainawabganj: "Rajshahi",
    Joypurhat: "Rajshahi",
    Naogaon: "Rajshahi",
    Natore: "Rajshahi",
    Pabna: "Rajshahi",
    Rajshahi: "Rajshahi",
    Sirajganj: "Rajshahi",

    // Rangpur Division
    Dinajpur: "Rangpur",
    Gaibandha: "Rangpur",
    Kurigram: "Rangpur",
    Lalmonirhat: "Rangpur",
    Nilphamari: "Rangpur",
    Panchagarh: "Rangpur",
    Rangpur: "Rangpur",
    Thakurgaon: "Rangpur",

    // Sylhet Division
    Habiganj: "Sylhet",
    Moulvibazar: "Sylhet",
    Sunamganj: "Sylhet",
    Sylhet: "Sylhet",
  }

  return divisionMap[district] || ""
}

// All divisions
export const divisions = ["Barisal", "Chittagong", "Dhaka", "Khulna", "Mymensingh", "Rajshahi", "Rangpur", "Sylhet"]

// Helper function to get districts by division
export const getDistrictsByDivision = (division) => {
  return districts.filter((district) => getDivisionForDistrict(district) === division)
}
